### ISSUE TITLE
(bug) v1.0.0: README.md demo code not working

### ISSUE THREAD

**Issue by dublx** [rc0x03/node-osmosis#3]
Several issues I bumped into (sha 397005653fceabec90c5ee6772bdade62fb6312d)
After similar experience with Issue #1 I noticed that the package.json version is now 1.0.0, and npmjs.org only v0.0.3. So I cloned the repo and npm link'ed:
```shell
$ git clone git@github.com:rc0x03/node-osmosis.git
$ cd node-osmosis
$ npm link
#NPM logs go here...
needle@0.9.1 node_modules/needle
├── iconv-lite@0.4.7
└── debug@2.1.3 (ms@0.7.0)

libxmljs@0.13.0 node_modules/libxmljs
├── bindings@1.1.1
└── nan@1.5.1
$ cd ../osmosis-test
npm link osmosis
$ npm i
npm WARN package.json osmosis-test@1.0.0 No description
npm WARN package.json osmosis-test@1.0.0 No repository field.
npm WARN package.json osmosis-test@1.0.0 No README data
needle@0.9.1 node_modules/needle
├── iconv-lite@0.4.7
└── debug@2.1.3 (ms@0.7.0)
#index is the exact same demo code from README.md at commit 397005653fceabec90c5ee6772bdade62fb6312d
$ node index.js 
/Users/lf/sandbox/node-osmosis/lib/promise.js:110
	this.next.debugNext(msg);
	         ^
TypeError: Cannot read property 'debugNext' of undefined
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:11)
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:12)
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:12)
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:12)
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:12)
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:12)
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:12)
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:12)
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:12)
    at Promise.debugNext (/Users/lf/sandbox/node-osmosis/lib/promise.js:110:12)
```

After that I place a `if` in the lib/promise.js
```javascript
Promise.prototype.debugNext = function(msg) {
	if(this.next) this.next.debugNext(msg);
}
```
While this doesn't fix the issue at least then I was able to run the demo code.

Thanks, Luis

**Comment by rc0x03** [comment]
Fixed in the latest version
