### ISSUE TITLE
xmljs.node Error

### ISSUE THREAD

**Issue by Xavier-Tuttle-Haff** [rc0x03/node-osmosis#32]
When trying to require Osmosis I get the error below. I'm running node v0.10.25.

Thanks for looking it over.

/root/node_modules/osmosis/node_modules/libxmljs/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /root/node_modules/osmosis/node_modules/libxmljs/build/Release/xmljs.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/root/node_modules/osmosis/node_modules/libxmljs/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/root/node_modules/osmosis/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by Xavier-Tuttle-Haff** [comment]
Solved by using v.12
