### ISSUE TITLE
Unable to run on (X)Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by evandrix** [rc0x03/node-osmosis#5]
Trying to run your sample provided in the README that targets Craigslist after installing via `npm install -g` yields the following error:
(My $NODE_PATH is /usr/local/lib/node_modules)

```
/usr/local/lib/node_modules/osmosis/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/osmosis/node_modules/libxmljs/build/xmljs.node
 → /usr/local/lib/node_modules/osmosis/node_modules/libxmljs/build/Debug/xmljs.node
 → /usr/local/lib/node_modules/osmosis/node_modules/libxmljs/build/Release/xmljs.node
 → /usr/local/lib/node_modules/osmosis/node_modules/libxmljs/out/Debug/xmljs.node
 → /usr/local/lib/node_modules/osmosis/node_modules/libxmljs/Debug/xmljs.node
 → /usr/local/lib/node_modules/osmosis/node_modules/libxmljs/out/Release/xmljs.node
 → /usr/local/lib/node_modules/osmosis/node_modules/libxmljs/Release/xmljs.node
 → /usr/local/lib/node_modules/osmosis/node_modules/libxmljs/build/default/xmljs.node
 → /usr/local/lib/node_modules/osmosis/node_modules/libxmljs/compiled/1.6.3/linux/x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/osmosis/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/osmosis/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/osmosis/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:410:26)
```

**Comment by rc0x03** [comment]
Looks like libxmljs didn't install properly. Please run `npm install libxmljs` and post any errors.

**Comment by evandrix** [comment]
Following is the build log output from `sudo npm install` from the node-osmosis project root, ie trying to install the deps of node-osmosis as specified in package.json manually:

```
> libxmljs@0.13.0 install /usr/local/lib/node_modules/osmosis/node_modules/libxmljs
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/local/lib/node_modules/osmosis/node_modules/libxmljs/build'
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
  CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
  CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
  CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
  CC(target) Release/obj.target/libxml/vendor/libxml/error.o
  CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
  CC(target) Release/obj.target/libxml/vendor/libxml/list.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
../vendor/libxml/parser.c: In function 'xmlParseInNodeContext':
../vendor/libxml/parser.c:13492:9: warning: pointer targets in passing argument 1 of 'xmlFindCharEncodingHandler' differ in signedness [-Wpointer-sign]
         hdlr = xmlFindCharEncodingHandler(doc->encoding);
         ^
In file included from ../vendor/libxml/include/libxml/parser.h:809:0,
                 from ../vendor/libxml/include/libxml/globals.h:18,
                 from ../vendor/libxml/include/libxml/threads.h:35,
                 from ../vendor/libxml/include/libxml/xmlmemory.h:218,
                 from ../vendor/libxml/parser.c:46:
../vendor/libxml/include/libxml/encoding.h:175:2: note: expected 'const char *' but argument is of type 'const xmlChar *'
  xmlFindCharEncodingHandler (const char *name);
  ^
  CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
  CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
  CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
  CC(target) Release/obj.target/libxml/vendor/libxml/uri.o
  CC(target) Release/obj.target/libxml/vendor/libxml/valid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xlink.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemas.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xpath.o
../vendor/libxml/xpath.c: In function 'xmlXPathNodeCollectAndTest':
../vendor/libxml/xpath.c:12401:28: warning: comparison between 'xmlElementType' and 'xmlXPathTypeVal' [-Wenum-compare]
       } else if (cur->type == type) {
                            ^
../vendor/libxml/xpath.c:12402:13: warning: comparison between 'xmlXPathTypeVal' and 'enum <anonymous>' [-Wenum-compare]
    if (type == XML_NAMESPACE_DECL)
             ^
In file included from ../vendor/libxml/xpath.c:185:0:
../vendor/libxml/xpath.c: At top level:
../vendor/libxml/trionan.c:218:1: warning: 'trio_is_negative' defined but not used [-Wunused-function]
 trio_is_negative
 ^
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
../vendor/libxml/xpointer.c: In function 'xmlXPtrNewRangeNodePoint':
../vendor/libxml/xpointer.c:451:21: warning: comparison between 'xmlElementType' and 'enum <anonymous>' [-Wenum-compare]
     if (start->type != XPATH_POINT)
                     ^
  AR(target) Release/obj.target/vendor/libxml/xml.a
  COPY Release/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
  CXX(target) Release/obj.target/xmljs/src/xml_document.o
  CXX(target) Release/obj.target/xmljs/src/xml_element.o
  CXX(target) Release/obj.target/xmljs/src/xml_comment.o
  CXX(target) Release/obj.target/xmljs/src/xml_namespace.o
  CXX(target) Release/obj.target/xmljs/src/xml_node.o
  CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
  CXX(target) Release/obj.target/xmljs/src/xml_syntax_error.o
  CXX(target) Release/obj.target/xmljs/src/xml_xpath_context.o
  SOLINK(target) Release/obj.target/xmljs.node
  SOLINK(target) Release/obj.target/xmljs.node: Finished
  COPY Release/lib.target/xmljs.node
make: Leaving directory `/usr/local/lib/node_modules/osmosis/node_modules/libxmljs/build'
needle@0.8.2 node_modules/needle
└── iconv-lite@0.4.7

libxmljs@0.13.0 node_modules/libxmljs
├── bindings@1.1.1
└── nan@1.5.1
```

**Comment by evandrix** [comment]
Ok, nvm I've sorted it out.

Turns out my $PATH was causing the Node from https://iojs.org/en/index.html to run instead.

Sigh.
