### ISSUE TITLE
Error when crawling thousands of pages

### ISSUE THREAD

**Issue by jperelli** [rc0x03/node-osmosis#51]
This is my config

```
  osmosis
  .config({proxy: 'localhost:8118'})
  .get(url)
  .paginate('#fecha_logo>a+img+a')
  .find('h2>a,#bloque_titulares h3>a')
  .follow('@href')
  .set({
    'title':        'h2',
    'subtitle':     '.volanta',
    'content1':     '.intro',
    'content2':     '#cuerpo',
    'html':         'html'
  })
  .then(function(context, data, next) {
    var url = context.doc().request.url;
    var u = url.split("-");
    var date = new Date(u[2], u[3]-1, u[4].split('.')[0]);
    var article = new Article({
      title: iconv.decode(data.title, "utf-8"),
      subtitle: iconv.decode(data.subtitle, "utf-8"),
      content: htmlToText.fromString(iconv.decode(data.content1 + data.content2, "utf-8")),
      html: data.html,
      url: url,
      date: date
    });
    article.save(function (err, obj) {
      if (err) console.log('Error saving: ' + err);
      console.log('     [' + obj.date + '] ' + obj.title);
    });
    next(context, data);
  })
  .log(console.log)
  .error(console.log)
  .debug(console.log);
```

Is this error from something in osmosis?
```
(get) Error: socket hang up
[get] http://www.pagina12.com.ar/diario/elmundo/4-263946-2015-01-15.html tries: 1 - socket hang up
/home/jperelli/crawler/node_modules/osmosis/lib/promises.js:411
                    data.obj[key] = getContent(context.get(val));
                                                      ^

TypeError: Cannot read property 'get' of null
    at loopObject (/home/jperelli/crawler/node_modules/osmosis/lib/promises.js:411:55)
    at Promise.set [as cb] (/home/jperelli/crawler/node_modules/osmosis/lib/promises.js:416:9)
    at Promise.start (/home/jperelli/crawler/node_modules/osmosis/lib/promise.js:227:9)
    at /home/jperelli/crawler/node_modules/osmosis/lib/promise.js:217:81
    at /home/jperelli/crawler/node_modules/osmosis/lib/promises.js:148:25
    at /home/jperelli/crawler/node_modules/osmosis/lib/promise.js:266:5
    at /home/jperelli/crawler/node_modules/osmosis/index.js:231:13
    at done (/home/jperelli/crawler/node_modules/osmosis/node_modules/needle/lib/needle.js:357:7)
    at ClientRequest.had_error (/home/jperelli/crawler/node_modules/osmosis/node_modules/needle/lib/needle.js:364:5)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketCloseListener (_http_client.js:235:9)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

**Comment by rc0x03** [comment]
This is due to a change that caused `follow` to improperly handle HTTP errors. It's fixed in the latest commit and will be fixed in the next version.

**Comment by jperelli** [comment]
ok, by next version I understand you mean the version published in npm?
