### ISSUE TITLE
Error "Can't set headers after they are sent"

### ISSUE THREAD

**Issue by aalireza439** [rc0x03/node-osmosis#56]
I want scrape a website and send data to express.js route
here is my code :

model.js
```javascript
var osmosis = require('osmosis');

var bing = function(keyword,callback){
	
	osmosis.get('http://www.bing.com/search?q='+keyword)
	.find('#b_results > li.b_algo')
	.set({
		title: 'h2',
		description: 'p',
		url: 'a@href'
	})
	.data(function(results) {
		callback(null,results);
	})
	.error(function(err){
		callback(err)
	})
}

exports.search = function(keyword , callback) {
	bing(keyword,function(err,results){
		if(err){
			callback(err);
		}else{
			
			callback(null,results);
			
		}
		
	})				
}
```

route
```javascript
router.get('/:keyword', function(req, res, next) {
  var keyword = encodeURI(req.params.keyword.replace(/-|\//g, " "));
  
  searchModel.search(keyword,function(err,results){
	  if(err){
		  console.log(err)
	  }else{
		  res.json(results)
	  }
  })		
  
});
```

when i run my express app show me this error:

```javascript
throw new Error('Can\'t set headers after they are sent.');

    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.header (/home/zoe/app/node_modules/express/lib/response.js:718:10)
    at ServerResponse.json (/home/zoe/app/node_modules/express/lib/response.js:246:10)
    at ServerResponse.send (/home/zoe/app/node_modules/express/lib/response.js:151:21)
    at /home/zoe/app/routes/search.js:13:9
    at /home/zoe/app/models/news.js:92:4
    at null.<anonymous> (/home/zoe/app/models/news.js:78:3)
    at Promise.data [as cb] (/home/zoe/app/node_modules/osmosis/lib/promises.js:40:16)
    at Promise.start (/home/zoe/app/node_modules/osmosis/lib/promise.js:168:9)
    at /home/zoe/app/node_modules/osmosis/lib/promise.js:168:62
    at loopObject (/home/zoe/app/node_modules/osmosis/lib/promises.js:398:24)
    at loopObject (/home/zoe/app/node_modules/osmosis/lib/promises.js:447:17)
    at loopObject (/home/zoe/app/node_modules/osmosis/lib/promises.js:447:17)
    at loopObject (/home/zoe/app/node_modules/osmosis/lib/promises.js:447:17)
    at Promise.set [as cb] (/home/zoe/app/node_modules/osmosis/lib/promises.js:450:9)
    at Promise.start (/home/zoe/app/node_modules/osmosis/lib/promise.js:168:9)

```

Update:
i am using osmosis 0.1.0
and without using express osmosis  working well.

**Comment by aalireza439** [comment]
i found problem , it was really silly mistake :(
when i get result form osmosis it iterate the data and run `res.json` multiple time and that cause problem.

i solved this by sending data to an array and then show in my route.

here is the my sample code :

```javascript
var google = function(keyword,callback){
	var data = [];
	osmosis.get('https://www.mydomain.com/')
	.find('.g')
	.set({
		title: 'h3',
		description:'.st',
		url:'.r > a@href'
	})
	.data(function(results) {
		data.push(results)
	})
	.error(function(err){
		callback(err)
	})
	 .done(function(){
        callback(null,data)
    });
}
```
