### ISSUE TITLE
Failed at the libxmljs@0.16.0 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by Ivanca** [rc0x03/node-osmosis#60]
This is what I get when I try to install osmosis 0.0.9 on Windows 8.1

```
732 verbose stack Error: libxmljs@0.16.0 install: `node-gyp rebuild`
732 verbose stack Exit status 1
732 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
732 verbose stack     at emitTwo (events.js:87:13)
732 verbose stack     at EventEmitter.emit (events.js:172:7)
732 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
732 verbose stack     at emitTwo (events.js:87:13)
732 verbose stack     at ChildProcess.emit (events.js:172:7)
732 verbose stack     at maybeClose (internal/child_process.js:818:16)
732 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
733 verbose pkgid libxmljs@0.16.0
734 verbose cwd C:\Users\Ivan\Dropbox\labs\carmax-scraper
735 error Windows_NT 6.3.9600
736 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "libxmljs-dom"
737 error node v4.2.1
738 error npm  v2.14.7
739 error code ELIFECYCLE
740 error libxmljs@0.16.0 install: `node-gyp rebuild`
740 error Exit status 1
741 error Failed at the libxmljs@0.16.0 install script 'node-gyp rebuild'.
741 error This is most likely a problem with the libxmljs package,
741 error not with npm itself.
741 error Tell the author that this fails on your system:
741 error     node-gyp rebuild
741 error You can get their info via:
741 error     npm owner ls libxmljs
741 error There is likely additional logging output above.
742 verbose exit [ 1, true ]
743 verbose unbuild node_modules\libxmljs-dom\node_modules\libxmljs
744 info preuninstall libxmljs@0.16.0
745 info uninstall libxmljs@0.16.0
746 verbose unbuild rmStuff libxmljs@0.16.0 from C:\Users\Ivan\Dropbox\labs\carmax-scraper\node_modules
747 verbose unbuild rmStuff in C:\Users\Ivan\Dropbox\labs\carmax-scraper\node_modules\libxmljs-dom\node_modules
748 info postuninstall libxmljs@0.16.0
749 silly gentlyRm C:\Users\Ivan\Dropbox\labs\carmax-scraper\node_modules\libxmljs-dom\node_modules\libxmljs is being purged from base C:\Users\Ivan\Dropbox\labs\carmax-scraper
750 verbose gentlyRm don't care about contents; nuking C:\Users\Ivan\Dropbox\labs\carmax-scraper\node_modules\libxmljs-dom\node_modules\libxmljs
751 silly vacuum-fs purging C:\Users\Ivan\Dropbox\labs\carmax-scraper\node_modules\libxmljs-dom\node_modules\libxmljs
752 silly vacuum-fs removing C:\Users\Ivan\Dropbox\labs\carmax-scraper\node_modules\libxmljs-dom\node_modules
753 silly vacuum-fs quitting because other entries in C:\Users\Ivan\Dropbox\labs\carmax-scraper\node_modules\libxmljs-dom
754 verbose unbuild node_modules\libxmljs-dom
755 info preuninstall libxmljs-dom@0.0.2
756 info uninstall libxmljs-dom@0.0.2
```

**Comment by VPlatoon** [comment]
I encountered a similar error. Make sure you installed `libxmljs`, i.e. 
```
npm install libxmljs
```
before installing `osmosis`. You may have to remove the `node-gyp` in order to be able to install libxmljs successfully.

**Comment by Ivanca** [comment]
Thanks but that isn't helping.

Looks like this issue is a gigantic rabbit hole:
https://github.com/nodejs/node-gyp/issues/573
https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

The error I'm getting now is:
```
xml_node.obj : error LNK2001: unresolved external symbol "struct _xmlNode * __cdecl libxmljs::get_wrapped_node_in_children(struct _xmlNode *,void *)" (?get_wrapped_node_in_ch ildren@libxmljs@@YAPEAU_xmlNode@@PEAU2@PEAX@Z) [C:\Users\Ivan\Dropbox\labs\cs\node_modules\libxmljs\build\xmljs.vcxproj]
C:\Users\Ivan\Dropbox\labs\cs\node_modules\libxmljs\build\Release\xmljs.node : fatal error LNK1120: 1 unresolved externals [C:\Users\Ivan\Dropbox\labs\cs\node_modules\libxmlj s\build\xmljs.vcxproj]
```

I will post a solution if I found any.

**Comment by rc0x03** [comment]
See https://github.com/polotek/libxmljs/issues/371

**Comment by Ivanca** [comment]
I'm getting a similar error despite being the new version... after much reading it seems the problem is always at compiling, so if you can ever change osmosis to not use compiling-on-installation stuff (e.g. no libxmljs) that would be amazing.

**Comment by NegativeIQ** [comment]
Just to drop something that might be related, but on Windows 7 SP1 x86
I had python 2.7.x and VS 2015 (not sure if i updated it to SP1) and i also had some issue installing osmosis since it was spitting some errors about compiling. Running npm with elevated rights (running cli as administrator) solved problem.
